name: Project TinyCC

on:
  workflow_dispatch

jobs:
  run:
    runs-on: self-hosted
    name: CI Build
    steps:
    - name: Configure
      run: |
        /bin/bash "$LOG_HOOK" TIMESTAMP BUILD_START "$(date -Ins)"
        ./configure
        /bin/bash "$LOG_HOOK" TIMESTAMP POST_CONFIGURE "$(date -Ins)"
      working-directory: ./project_tinycc

    - name: Make
      run: |
        make -j4
        /bin/bash "$LOG_HOOK" TIMESTAMP POST_MAKE "$(date -Ins)"
      working-directory: ./project_tinycc

    - name: Make check
      run: |
        # make test -j4
        /bin/bash "$LOG_HOOK" TIMESTAMP POST_MAKE_CHECK "$(date -Ins)"
        /bin/bash "$LOG_HOOK" TIMESTAMP BUILD_END "$(date -Ins)"
      working-directory: ./project_tinycc

    - name: Run attestation
      run: /bin/bash "$ATTESTATION_HOOK" "tcc"
      working-directory: ./project_tinycc
